# Project 4

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
def franke(x,y):
    return 3/4 * np.exp(- (9*x - 2)**2 /4 - (9*y -2)**2 /4) + 3/4 * np.exp(- (9*x + 1)**2 /49 - (9*y +1) /10) + 1/2* np.exp(- (9*x -7)**2 / 4 - (9*y - 3)**2 /4) - 1/5* np.exp(- (9*x -4)**2 - (9*y - 7)**2) 

## Making datapoints

In [3]:
X = np.random.rand(10000,2)
y = franke(X[:,0], X[:,1])
print(X.shape)
print(y.shape)


(10000, 2)
(10000,)


## OLS with gradient descent

In [4]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

def f(x, y, b):
    return (b[0] + b[1]*x[:,0] + b[2]*x[:,1] - y)

def res(x, y, b):
    return sum(f(x,y, b)*f(x, y, b))

def grad(x, y, b):
    return np.array([
            sum(f(x, y, b)),
            sum(x[:,0]*f(x, y, b)),
            sum(x[:,1]*f(x, y, b))
    ])

def gd(b_start, gradient, max_iter, learning_rate):
    b = np.array(b_start, dtype='float64')
    print(b)
    for i in range(max_iter):
        grad = gradient(X_train, y_train, b)
        b -= grad * learning_rate
        if i % 200 == 0:
            print(f"Iter {i}: resiudal {res(X_train, y_train, b)}") 
        if abs(sum(grad)) < 1e-7:
            break;
    print(f"Iter {i}: resiudal {res(X_train, y_train, b)}")
    return b

In [12]:
b_start = [0,0,0]
max_iter = 10000
learning_rate = 0.00001
bstar = gd(b_start, grad, max_iter, learning_rate)
bstar

[0. 0. 0.]
Iter 0: resiudal 1530.2153312433531
Iter 200: resiudal 293.03927695836103
Iter 400: resiudal 190.6476720530112
Iter 600: resiudal 168.12393232301883
Iter 800: resiudal 163.16035820940346
Iter 1000: resiudal 162.06571652526566
Iter 1200: resiudal 161.82423510702927
Iter 1400: resiudal 161.7709567107779
Iter 1600: resiudal 161.7592011957475
Iter 1800: resiudal 161.75660736429225
Iter 2000: resiudal 161.7560350352135
Iter 2200: resiudal 161.75590875028482
Iter 2400: resiudal 161.7558808853577
Iter 2600: resiudal 161.75587473692346
Iter 2800: resiudal 161.7558733802624
Iter 3000: resiudal 161.75587308091357
Iter 3200: resiudal 161.75587301486075
Iter 3400: resiudal 161.75587300028687
Iter 3600: resiudal 161.75587299707092
Iter 3800: resiudal 161.75587299636135
Iter 4000: resiudal 161.75587299620466
Iter 4200: resiudal 161.75587299616998
Iter 4400: resiudal 161.7558729961631
Iter 4600: resiudal 161.75587299616035
Iter 4800: resiudal 161.75587299616103
Iter 5000: resiudal 161.7558

array([ 0.99004635, -0.50949427, -0.66669848])

In [13]:
mse_train = np.mean(np.power(f(X_train,y_train,bstar)-y_train, 2))
mse_test = np.mean(np.power(f(X_test,y_test,bstar)-y_test, 2))
print(f"MSE using ols on train : {mse_train}")
print(f"MSE using ols on test : {mse_test}")

MSE using ols on train : 0.31630415327603273
MSE using ols on test : 0.3131597526632503


## Ridge Regression

In [8]:
l = 0.1

def grad_ridge(x, y, b):
    return np.array([
            sum(f(x, y, b)) + 2*l*b[0],
            sum(x[:,0]*f(x, y, b)) + 2*l*b[1],
            sum(x[:,1]*f(x, y, b)) + 2*l*b[2]
    ])

b_start = [0,0,0]
max_iter = 10000
learning_rate = 0.00001
bstar = gd(b_start, grad_ridge, max_iter, learning_rate)
bstar

[0. 0. 0.]
Iter 0: resiudal 1530.2153312433531
Iter 200: resiudal 293.09186305187336
Iter 400: resiudal 190.7101076093674
Iter 600: resiudal 168.1673631438506
Iter 800: resiudal 163.18519454318795
Iter 1000: resiudal 162.0787061386296
Iter 1200: resiudal 161.8307582073965
Iter 1400: resiudal 161.77419635715557
Iter 1600: resiudal 161.7608340900215
Iter 1800: resiudal 161.75746916242562
Iter 2000: resiudal 161.7565305879002
Iter 2200: resiudal 161.7562313005965
Iter 2400: resiudal 161.75612195083528
Iter 2600: resiudal 161.75607748055944
Iter 2800: resiudal 161.75605811542147
Iter 3000: resiudal 161.75604935678794
Iter 3200: resiudal 161.75604531788898
Iter 3400: resiudal 161.7560434376852
Iter 3600: resiudal 161.75604255842427
Iter 3800: resiudal 161.75604214636
Iter 4000: resiudal 161.75604195305178
Iter 4200: resiudal 161.75604186232187
Iter 4400: resiudal 161.7560418197288
Iter 4600: resiudal 161.7560417997313
Iter 4800: resiudal 161.7560417903419
Iter 5000: resiudal 161.75604178593

array([ 0.98964508, -0.50914448, -0.66629516])

In [7]:
mse_train = np.mean(np.power(f(X_train,y_train,bstar)-y_train, 2))
mse_test = np.mean(np.power(f(X_test,y_test,bstar)-y_test, 2))
print(f"MSE using ols on train : {mse_train}")
print(f"MSE using ols on test : {mse_test}")

MSE using ols on train : 0.31640037260886505
MSE using ols on test : 0.3132511193718508


In [10]:
l = 1
bstar = gd(b_start, grad_ridge, max_iter, learning_rate)
mse_train = np.mean(np.power(f(X_train,y_train,bstar)-y_train, 2))
mse_test = np.mean(np.power(f(X_test,y_test,bstar)-y_test, 2))
print(f"MSE using ols on train : {mse_train}")
print(f"MSE using ols on test : {mse_test}")

[0. 0. 0.]
Iter 0: resiudal 1530.2153312433531
Iter 200: resiudal 293.5650553711091
Iter 400: resiudal 191.27379621651878
Iter 600: resiudal 168.5636623001126
Iter 800: resiudal 163.41765698455168
Iter 1000: resiudal 162.2070865527713
Iter 1200: resiudal 161.90252702113298
Iter 1400: resiudal 161.8173288832136
Iter 1600: resiudal 161.79000819799214
Iter 1800: resiudal 161.77997101720607
Iter 2000: resiudal 161.77587598838855
Iter 2200: resiudal 161.774091671334
Iter 2400: resiudal 161.7732856768663
Iter 2600: resiudal 161.77291489709083
Iter 2800: resiudal 161.77274280792713
Iter 3000: resiudal 161.77266259804264
Iter 3200: resiudal 161.77262513788915
Iter 3400: resiudal 161.77260762656866
Iter 3600: resiudal 161.77259943702802
Iter 3800: resiudal 161.77259560622358
Iter 4000: resiudal 161.77259381412367
Iter 4200: resiudal 161.77259297571717
Iter 4400: resiudal 161.77259258347294
Iter 4600: resiudal 161.77259239996215
Iter 4800: resiudal 161.7725923141071
Iter 5000: resiudal 161.77259

In [11]:
l = 10
bstar = gd(b_start, grad_ridge, max_iter, learning_rate)
mse_train = np.mean(np.power(f(X_train,y_train,bstar)-y_train, 2))
mse_test = np.mean(np.power(f(X_test,y_test,bstar)-y_test, 2))
print(f"MSE using ols on train : {mse_train}")
print(f"MSE using ols on test : {mse_test}")

[0. 0. 0.]
Iter 0: resiudal 1530.2153312433531
Iter 200: resiudal 298.28819818248417
Iter 400: resiudal 197.07463763426406
Iter 600: resiudal 173.02660903907608
Iter 800: resiudal 166.5590337421261
Iter 1000: resiudal 164.53187306057796
Iter 1200: resiudal 163.7985692859224
Iter 1400: resiudal 163.5046314701731
Iter 1600: resiudal 163.3795268527513
Iter 1800: resiudal 163.32461020598075
Iter 2000: resiudal 163.3001427907184
Iter 2200: resiudal 163.2891659968972
Iter 2400: resiudal 163.2842258549635
Iter 2600: resiudal 163.28199931663784
Iter 2800: resiudal 163.28099515004692
Iter 3000: resiudal 163.2805421368737
Iter 3200: resiudal 163.2803377397175
Iter 3400: resiudal 163.28024551107865
Iter 3600: resiudal 163.28020389423844
Iter 3800: resiudal 163.28018511499326
Iter 4000: resiudal 163.2801766409674
Iter 4200: resiudal 163.2801728171001
Iter 4400: resiudal 163.28017109159467
Iter 4600: resiudal 163.28017031296696
Iter 4800: resiudal 163.28016996161313
Iter 5000: resiudal 163.28016980

## ANN from scratch

In [4]:
class FCLayer():
    # input_size = number of input neurons
    # output_size = number of output neurons
    def __init__(self, input_size, output_size):
        self.weights = np.random.normal(size = (input_size, output_size))
        self.bias = np.random.normal(size = (1, output_size))

    # returns output for a given input
    def forward_propagation(self, input_data):
        self.input = input_data
        self.output = np.dot(self.input, self.weights) + self.bias
        return self.output

    # computes dE/dW, dE/dB for a given output_error=dE/dA_l. Returns input_error=dE/dAl-1.
    def backward_propagation(self, output_error, learning_rate):
        input_error = np.dot(output_error, self.weights.T)
        weights_error = np.dot(self.input.T, output_error)
        # dBias = output_error

        # update parameters
        self.weights -= learning_rate * weights_error
        self.bias -= learning_rate * output_error
        return input_error

In [5]:
class ActivationLayer():
    def __init__(self, activation, activation_prime):
        self.activation = activation
        self.activation_prime = activation_prime

    # returns the activated input
    def forward_propagation(self, input_data):
        self.input = input_data
        self.output = self.activation(self.input)
        return self.output

    # Returns input_error=dE/dX for a given output_error=dE/dY.
    # learning_rate is not used because there is no "learnable" parameters.
    def backward_propagation(self, output_error, learning_rate):
        return self.activation_prime(self.input) * output_error

In [6]:
def tanh(x):
    return np.tanh(x);

def tanh_prime(x):
    return 1-np.tanh(x)**2;

def sigmoid(x):
    return 1/(1+np.exp(-x))

def sigmoid_prime(x):
    return sigmoid(x)*(1 - sigmoid(x))

def relu(x):
    return np.maximum(x, 0)

def relu_prime(x):
    return np.greater(x, 0).astype(int)
    

In [7]:
# loss function and its derivative
def mse(y_true, y_pred):
    return np.mean(np.power(y_true-y_pred, 2));

def mse_prime(y_true, y_pred):
    return 2*(y_pred-y_true)/y_true.size;

In [8]:
class Network:
    def __init__(self):
        self.layers = []
        self.loss = None
        self.loss_prime = None

    # add layer to network
    def add(self, layer):
        self.layers.append(layer)

    # set loss to use
    def use(self, loss, loss_prime):
        self.loss = loss
        self.loss_prime = loss_prime

    # predict output for given input
    def predict(self, input_data):
        # sample dimension first
        samples = len(input_data)
        result = []

        # run network over all samples
        for i in range(samples):
            # forward propagation
            output = input_data[i]
            for layer in self.layers:
                output = layer.forward_propagation(output)
            result.append(output)

        return result
    
    # train the network
    def fit(self, x_train, y_train, epochs, learning_rate):
        # sample dimension first
        samples = len(x_train)

        # training loop
        for i in range(epochs):
            err = 0
            for j in range(samples):
                # forward propagation
                output = x_train[j]
                for layer in self.layers:
                    output = layer.forward_propagation(output)

                # compute loss (for display purpose only)
                err += self.loss(y_train[j], output)

                # backward propagation
                error = self.loss_prime(y_train[j], output)
                for layer in reversed(self.layers):
                    error = layer.backward_propagation(error, learning_rate)

            # calculate average error on all samples
            err /= samples
        
            print('epoch %d/%d   error=%f' % (i+1, epochs, err))

In [9]:
X = X.reshape(10000, 1, 2)
y = y.reshape(10000, 1 ,1)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
# network
net = Network()
net.add(FCLayer(2, 20))
net.add(ActivationLayer(tanh, tanh_prime))
net.add(FCLayer(20, 10))
net.add(ActivationLayer(tanh, tanh_prime))
net.add(FCLayer(10, 1))
net.add(ActivationLayer(tanh, tanh_prime))

# train
net.use(mse, mse_prime)
net.fit(X_train, y_train, epochs= 15, learning_rate=0.01)



epoch 1/15   error=0.168115
epoch 2/15   error=0.007644
epoch 3/15   error=0.006889
epoch 4/15   error=0.006695
epoch 5/15   error=0.006593
epoch 6/15   error=0.006514
epoch 7/15   error=0.006446
epoch 8/15   error=0.006385
epoch 9/15   error=0.006329
epoch 10/15   error=0.006277
epoch 11/15   error=0.006228
epoch 12/15   error=0.006181
epoch 13/15   error=0.006137
epoch 14/15   error=0.006096
epoch 15/15   error=0.006056


In [10]:
mse_train = np.mean(np.power(net.predict(X_train)-y_train, 2))
mse_test = np.mean(np.power(net.predict(X_test)-y_test, 2))
print(f"MSE using ols on train : {mse_train}")
print(f"MSE using ols on test : {mse_test}")

MSE using ols on train : 0.006124849349267002
MSE using ols on test : 0.00596695522880237


In [11]:
# network
net = Network()
net.add(FCLayer(2, 20))
net.add(ActivationLayer(relu, relu_prime))
net.add(FCLayer(20, 10))
net.add(ActivationLayer(relu, relu_prime))
net.add(FCLayer(10, 1))
net.add(ActivationLayer(tanh, tanh_prime))

# train
net.use(mse, mse_prime)
net.fit(X_train, y_train, epochs=15, learning_rate=0.01)

epoch 1/15   error=0.085031
epoch 2/15   error=0.010259
epoch 3/15   error=0.008299
epoch 4/15   error=0.006928
epoch 5/15   error=0.005408
epoch 6/15   error=0.004409
epoch 7/15   error=0.003998
epoch 8/15   error=0.003786
epoch 9/15   error=0.003652
epoch 10/15   error=0.003544
epoch 11/15   error=0.003445
epoch 12/15   error=0.003367
epoch 13/15   error=0.003287
epoch 14/15   error=0.003227
epoch 15/15   error=0.003179


In [12]:
mse_train = np.mean(np.power(net.predict(X_train)-y_train, 2))
mse_test = np.mean(np.power(net.predict(X_test)-y_test, 2))
print(f"MSE using ols on train : {mse_train}")
print(f"MSE using ols on test : {mse_test}")

MSE using ols on train : 0.0028292818309489077
MSE using ols on test : 0.00273919293654


In [13]:
# network
net = Network()
net.add(FCLayer(2, 20))
net.add(ActivationLayer(sigmoid, sigmoid_prime))
net.add(FCLayer(20, 10))
net.add(ActivationLayer(sigmoid, sigmoid_prime))
net.add(FCLayer(10, 1))
net.add(ActivationLayer(tanh, tanh_prime))

# train
net.use(mse, mse_prime)
net.fit(X_train, y_train, epochs=15, learning_rate=0.01)

epoch 1/15   error=0.035261
epoch 2/15   error=0.021940
epoch 3/15   error=0.020446
epoch 4/15   error=0.019693
epoch 5/15   error=0.019219
epoch 6/15   error=0.018893
epoch 7/15   error=0.018654
epoch 8/15   error=0.018472
epoch 9/15   error=0.018326
epoch 10/15   error=0.018207
epoch 11/15   error=0.018104
epoch 12/15   error=0.018013
epoch 13/15   error=0.017931
epoch 14/15   error=0.017854
epoch 15/15   error=0.017780


In [14]:
mse_train = np.mean(np.power(net.predict(X_train)-y_train, 2))
mse_test = np.mean(np.power(net.predict(X_test)-y_test, 2))
print(f"MSE using ols on train : {mse_train}")
print(f"MSE using ols on test : {mse_test}")

MSE using ols on train : 0.0187771308907652
MSE using ols on test : 0.018516315885335297


In [15]:
# network
net = Network()
net.add(FCLayer(2, 20))
net.add(ActivationLayer(relu, relu_prime))
net.add(FCLayer(20, 10))
net.add(ActivationLayer(relu, relu_prime))
net.add(FCLayer(10, 1))
net.add(ActivationLayer(sigmoid, sigmoid_prime))

# train
net.use(mse, mse_prime)
net.fit(X_train, y_train, epochs=15, learning_rate=0.01)

epoch 1/15   error=0.041375
epoch 2/15   error=0.018077
epoch 3/15   error=0.010534
epoch 4/15   error=0.007362
epoch 5/15   error=0.006011
epoch 6/15   error=0.005206
epoch 7/15   error=0.004650
epoch 8/15   error=0.004248
epoch 9/15   error=0.004004
epoch 10/15   error=0.003876
epoch 11/15   error=0.003780
epoch 12/15   error=0.003700
epoch 13/15   error=0.003628
epoch 14/15   error=0.003564
epoch 15/15   error=0.003503


In [16]:
mse_train = np.mean(np.power(net.predict(X_train)-y_train, 2))
mse_test = np.mean(np.power(net.predict(X_test)-y_test, 2))
print(f"MSE using ols on train : {mse_train}")
print(f"MSE using ols on test : {mse_test}")

MSE using ols on train : 0.003428019180475225
MSE using ols on test : 0.0032911804437067474


## Using tensorflow/keras

In [19]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

model = keras.Sequential(
    [
        layers.Dense(20, activation = 'relu'),
        layers.Dense(10, activation = 'relu'),
        layers.Dense(1, activation = 'tanh'),
    ]
)

model.compile(
    loss = keras.losses.MeanSquaredError(),
    optimizer = keras.optimizers.SGD()
)

model.fit(X_train.reshape(-1,2),y_train.reshape(-1,1), epochs = 15)

Epoch 1/15
219/219 [==============================] - 0s 619us/step - loss: 0.0870
Epoch 2/15
219/219 [==============================] - 0s 610us/step - loss: 0.0456
Epoch 3/15
219/219 [==============================] - 0s 619us/step - loss: 0.0322
Epoch 4/15
219/219 [==============================] - 0s 612us/step - loss: 0.0270
Epoch 5/15
219/219 [==============================] - 0s 619us/step - loss: 0.0247
Epoch 6/15
219/219 [==============================] - 0s 615us/step - loss: 0.0234
Epoch 7/15
219/219 [==============================] - 0s 616us/step - loss: 0.0227
Epoch 8/15
219/219 [==============================] - 0s 619us/step - loss: 0.0222
Epoch 9/15
219/219 [==============================] - 0s 610us/step - loss: 0.0218
Epoch 10/15
219/219 [==============================] - 0s 615us/step - loss: 0.0215
Epoch 11/15
219/219 [==============================] - 0s 615us/step - loss: 0.0212
Epoch 12/15
219/219 [==============================] - 0s 619us/step - loss: 0.0210
E

In [20]:
model.evaluate(X_test.reshape(-1,2), y_test.reshape(-1,1))

94/94 [==============================] - 0s 559us/step - loss: 0.0200


0.02001296915113926

## Neural Network for Binary Classification

In [21]:
from sklearn.datasets import load_breast_cancer
breast_cancer = load_breast_cancer()

df = pd.DataFrame(data=breast_cancer.data, columns=breast_cancer.feature_names)

df["target"] = breast_cancer.target

In [22]:
y = np.array(df['target']).reshape(-1,1,1)
x = np.array(df.drop('target', axis = 1)).reshape(-1,1,30)
print(x.shape, y.shape)

(569, 1, 30) (569, 1, 1)


In [270]:
# loss function and its derivative
def negative_log_loss(y_true, y_pred):
    return -(y_true * np.log(y_pred) + (1 - y_true)*np.log(1- y_pred))

def negative_log_loss_prime(y_true, y_pred):
    return -(y_true + y_pred)/(y_pred*(1- y_pred)*y_true.size);

negative_log_loss(1, 0.1)

2.3025850929940455

In [25]:
def linear(x):
    return x

def linear_prime(x):
    return 1

In [273]:
# network
net = Network()
net.add(FCLayer(30, 30))
net.add(ActivationLayer(tanh, tanh_prime))
net.add(FCLayer(30, 20))
net.add(ActivationLayer(sigmoid, sigmoid_prime))
net.add(FCLayer(20, 1))
net.add(ActivationLayer(sigmoid, sigmoid_prime))

# train
net.use(negative_log_loss, negative_log_loss_prime)
net.fit(x, y, epochs= 30, learning_rate=0.000005)

epoch 1/30   error=1.548828
epoch 2/30   error=1.076472
epoch 3/30   error=0.809425
epoch 4/30   error=0.786945
epoch 5/30   error=0.763921
epoch 6/30   error=0.742671
epoch 7/30   error=0.722429
epoch 8/30   error=0.702515
epoch 9/30   error=0.688431
epoch 10/30   error=0.675819
epoch 11/30   error=0.662931
epoch 12/30   error=0.649694
epoch 13/30   error=0.635807
epoch 14/30   error=0.623137
epoch 15/30   error=0.611828
epoch 16/30   error=0.601393
epoch 17/30   error=0.586184
epoch 18/30   error=0.574554
epoch 19/30   error=0.564809
epoch 20/30   error=0.555285
epoch 21/30   error=0.546716
epoch 22/30   error=0.537940
epoch 23/30   error=0.529294
epoch 24/30   error=0.520908
epoch 25/30   error=0.513514
epoch 26/30   error=0.507127
epoch 27/30   error=0.499807
epoch 28/30   error=0.493315
epoch 29/30   error=0.487842
epoch 30/30   error=0.483415


In [274]:
y_predict = net.predict(x)
y_predict_label = np.zeros((y.shape[0],1))
i = 0
for prediction in y_predict:
    if prediction[0] >= 0.5:
        y_predict_label[i] = 1
    else:
        y_predict_label[i] = 0
    i = i+1

y_true = y[:,0]

correct_classified = 0
for i in range(len(y_predict_label)):
    if y_predict_label[i] == y_true[i]:
        correct_classified += 1
        
print(f"Accuracy: {correct_classified/y_true.shape[0]}")

Accuracy: 0.8892794376098418


## Logistic Regression

In [25]:
x = x.reshape(-1,30)
y = y.reshape(-1,1)


In [29]:
def weightInitialization(n_features):
    w = np.zeros((1, n_features))
    b = 0
    return w,b

def sigmoid_activation(x):
    return  1/(1+np.exp(-x))

def logistic_regr_fit(w,b,X,Y, learning_rate,n_iter = 1000):
    for i in range(n_iter):
        m = X.shape[0]
    
        #Prediction
        a = sigmoid_activation(np.dot(w,X.T)+b)
        Y_T = Y.T
        cost = (-1/m)*(np.sum((Y_T*np.log(a)) + ((1-Y_T)*(np.log(1-a)))))
      
    
        #Gradient calculation
        dw = (1/m)*(np.dot(X.T, (a-Y.T).T))
        db = (1/m)*(np.sum(a-Y.T))
    
        #weight update
        w = w - (learning_rate * (dw.T))
        b = b - (learning_rate * db)
        #
        
        if (i % 100 == 0):
            print("Iter %i: Negative Log loss is %f" %(i, cost))
        
    return w, b
    

In [37]:
w,b = weightInitialization(x.shape[1])
w,b = logistic_regr_fit(w,b,x,y, 0.000005, n_iter = 1000)



Iter 0: Negative Log loss is 0.693147
Iter 100: Negative Log loss is 0.515389
Iter 200: Negative Log loss is 0.448926
Iter 300: Negative Log loss is 0.409006
Iter 400: Negative Log loss is 0.381209
Iter 500: Negative Log loss is 0.360256
Iter 600: Negative Log loss is 0.343685
Iter 700: Negative Log loss is 0.330165
Iter 800: Negative Log loss is 0.318896
Iter 900: Negative Log loss is 0.309358


In [39]:
y_predict = sigmoid_activation(np.dot(w,x.T)+b).T
y_predict_label = np.zeros((y.shape[0],1))
i = 0
for prediction in y_predict:
    if prediction >= 0.5:
        y_predict_label[i] = 1
    else:
        y_predict_label[i] = 0
    i = i+1

y_true = y[:,0]

correct_classified = 0
for i in range(len(y_predict_label)):
    if y_predict_label[i] == y_true[i]:
        correct_classified += 1
        
print(f"Accuracy: {correct_classified/y_true.shape[0]}")

Accuracy: 0.9121265377855887


## Using tensorflow/keras

In [52]:
model = keras.Sequential(
    [
        layers.Dense(30, activation = 'relu'),
        layers.Dense(20, activation = 'relu'),
        layers.Dense(1, activation = 'sigmoid'),
    ]
)

model.compile(
    loss = keras.losses.BinaryCrossentropy(),
    optimizer = keras.optimizers.SGD(learning_rate = 0.00005),
    metrics = ["accuracy"]
)

model.fit(x,y, epochs = 30)
model.evaluate(x,y)

Epoch 1/30
18/18 [==============================] - 0s 882us/step - loss: 14.2444 - accuracy: 0.6063
Epoch 2/30
18/18 [==============================] - 0s 765us/step - loss: 0.8706 - accuracy: 0.8366
Epoch 3/30
18/18 [==============================] - 0s 824us/step - loss: 0.5422 - accuracy: 0.8594
Epoch 4/30
18/18 [==============================] - 0s 706us/step - loss: 0.5246 - accuracy: 0.8752
Epoch 5/30
18/18 [==============================] - 0s 765us/step - loss: 0.4561 - accuracy: 0.8928
Epoch 6/30
18/18 [==============================] - 0s 765us/step - loss: 0.4558 - accuracy: 0.8787
Epoch 7/30
18/18 [==============================] - 0s 765us/step - loss: 0.4253 - accuracy: 0.8858
Epoch 8/30
18/18 [==============================] - 0s 765us/step - loss: 0.4885 - accuracy: 0.8752
Epoch 9/30
18/18 [==============================] - 0s 765us/step - loss: 0.4301 - accuracy: 0.8946
Epoch 10/30
18/18 [==============================] - 0s 765us/step - loss: 0.4079 - accuracy: 0.896

[0.5851401686668396, 0.8892794251441956]